import { setHours, setMinutes, startOfWeek } from "date-fns";
import Timetable from "../components/timetable/Timetable";
import {
  AssignmentStatusEnum,
  AttendanceStatusEnum,
  LessonTypeEnum,
  LessonType,
} from "../types/lesson";
import { useMemo } from "react";
import { useDate } from "../hooks/useDate";

const lessons: LessonType[] = [
  {
    id: "1",
    date: new Date(2025, 1, 28, 8, 40),
    subjectName: "Physics",
    teacherName: "Alice Smith",
    teacherAvatar: "https://example.com/avatar1.jpg",
    room: "B203",
    type: LessonTypeEnum.Lecture,
    attendanceStatus: AttendanceStatusEnum.Excused,
    assignmentStatus: AssignmentStatusEnum.Overdue,
  },
  {
    id: "2",
    date: new Date(2025, 1, 28, 10, 35),
    subjectName: "Computer Science",
    teacherName: "Michael Johnson",
    teacherAvatar: "https://example.com/avatar2.jpg",
    link: "https://example.com/cs",
    type: LessonTypeEnum.Practice,
    attendanceStatus: AttendanceStatusEnum.Skipped,
    assignmentStatus: AssignmentStatusEnum.Submitted,
  },
  {
    id: "3",
    date: new Date(2025, 1, 28, 12, 20),
    subjectName: "History",
    teacherName: "Emma Wilson",
    teacherAvatar: "https://example.com/avatar3.jpg",
    link: "https://example.com/history",
    type: LessonTypeEnum.Seminar,
    attendanceStatus: AttendanceStatusEnum.Cancelled,
    assignmentStatus: AssignmentStatusEnum.Graded,
  },
  {
    id: "4",
    date: new Date(2025, 1, 28, 14, 5),
    subjectName: "Mathematics",
    teacherName: "John Doe",
    teacherAvatar: "https://example.com/avatar4.jpg",
    link: "https://example.com/math",
    room: "A101",
    type: LessonTypeEnum.Consultation,
    attendanceStatus: AttendanceStatusEnum.Unknown,
    assignmentStatus: AssignmentStatusEnum.Expired,
  },

  {
    id: "5",
    date: new Date(2025, 1, 27, 8, 40),
    subjectName: "Math",
    teacherName: "John Doe",
    teacherAvatar: "https://example.com/avatar.jpg",
    room: "A101",
    type: LessonTypeEnum.Lecture,
    attendanceStatus: AttendanceStatusEnum.Attended,
    assignmentStatus: AssignmentStatusEnum.Due,
  },
  {
    id: "6",
    date: new Date(2025, 1, 27, 10, 35),
    subjectName: "Physics",
    teacherName: "Jane Smith",
    teacherAvatar: "https://example.com/avatar2.jpg",
    link: "https://example.com/physics",
    room: "B202",
    type: LessonTypeEnum.Practice,
    attendanceStatus: AttendanceStatusEnum.Skipped,
    assignmentStatus: AssignmentStatusEnum.Overdue,
  },
  {
    id: "7",
    date: new Date(2025, 1, 27, 12, 20),
    subjectName: "History",
    teacherName: "Robert Brown",
    teacherAvatar: "https://example.com/avatar3.jpg",
    link: "https://example.com/history",
    type: LessonTypeEnum.Seminar,
    attendanceStatus: AttendanceStatusEnum.Excused,
    assignmentStatus: AssignmentStatusEnum.Submitted,
  },
  {
    id: "8",
    date: new Date(2025, 1, 27, 14, 5),
    subjectName: "Computer Science",
    teacherName: "Emily White",
    teacherAvatar: "https://example.com/avatar4.jpg",
    link: "https://example.com/cs",
    type: LessonTypeEnum.Consultation,
    attendanceStatus: AttendanceStatusEnum.Cancelled,
    assignmentStatus: AssignmentStatusEnum.Graded,
  },
  {
    id: "9",
    date: new Date(2025, 1, 26, 8, 40),
    subjectName: "Biology",
    teacherName: "Alice Green",
    teacherAvatar: "https://example.com/avatar5.jpg",
    link: "https://example.com/biology",
    room: "E505",
    type: LessonTypeEnum.Lecture,
    attendanceStatus: AttendanceStatusEnum.Unknown,
    assignmentStatus: AssignmentStatusEnum.Expired,
  },
  {
    id: "10",
    date: new Date(2025, 1, 26, 10, 35),
    subjectName: "Chemistry",
    teacherName: "Michael Johnson",
    teacherAvatar: "https://example.com/avatar6.jpg",
    link: "https://example.com/chemistry",
    room: "F606",
    type: LessonTypeEnum.Practice,
    attendanceStatus: AttendanceStatusEnum.Attended,
    assignmentStatus: AssignmentStatusEnum.Graded,
  },
  {
    id: "11",
    date: new Date(2025, 1, 26, 12, 20),
    subjectName: "Philosophy",
    teacherName: "Sophia Martinez",
    teacherAvatar: "https://example.com/avatar7.jpg",
    link: "https://example.com/philosophy",
    room: "G707",
    type: LessonTypeEnum.Seminar,
    attendanceStatus: AttendanceStatusEnum.Skipped,
    assignmentStatus: AssignmentStatusEnum.Due,
  },
  {
    id: "12",
    date: new Date(2025, 1, 26, 14, 5),
    subjectName: "Economics",
    teacherName: "Daniel Carter",
    teacherAvatar: "https://example.com/avatar8.jpg",
    link: "https://example.com/economics",
    room: "H808",
    type: LessonTypeEnum.Exam,
    attendanceStatus: AttendanceStatusEnum.Excused,
    assignmentStatus: AssignmentStatusEnum.Overdue,
  },
  {
    id: "13",
    date: new Date(2025, 1, 25, 8, 40),
    subjectName: "Math",
    teacherName: "John Doe",
    teacherAvatar: "https://example.com/avatar.jpg",
    room: "A101",
    type: LessonTypeEnum.Lecture,
    attendanceStatus: AttendanceStatusEnum.Attended,
    assignmentStatus: AssignmentStatusEnum.Due,
  },
  {
    id: "14",
    date: new Date(2025, 1, 25, 10, 35),
    subjectName: "Physics",
    teacherName: "Jane Smith",
    teacherAvatar: "https://example.com/avatar2.jpg",
    link: "https://example.com/physics",
    room: "B202",
    type: LessonTypeEnum.Practice,
    attendanceStatus: AttendanceStatusEnum.Skipped,
    assignmentStatus: AssignmentStatusEnum.Overdue,
  },
  {
    id: "15",
    date: new Date(2025, 1, 25, 12, 20),
    subjectName: "History",
    teacherName: "Robert Brown",
    teacherAvatar: "https://example.com/avatar3.jpg",
    link: "https://example.com/history",
    type: LessonTypeEnum.Seminar,
    attendanceStatus: AttendanceStatusEnum.Excused,
    assignmentStatus: AssignmentStatusEnum.Submitted,
  },
  {
    id: "16",
    date: new Date(2025, 1, 25, 14, 5),
    subjectName: "Computer Science",
    teacherName: "Emily White",
    teacherAvatar: "https://example.com/avatar4.jpg",
    link: "https://example.com/cs",
    type: LessonTypeEnum.Consultation,
    attendanceStatus: AttendanceStatusEnum.Cancelled,
    assignmentStatus: AssignmentStatusEnum.Graded,
  },
  {
    id: "17",
    date: new Date(2025, 1, 24, 8, 40),
    subjectName: "Physics",
    teacherName: "Alice Smith",
    teacherAvatar: "https://example.com/avatar1.jpg",
    room: "B203",
    type: LessonTypeEnum.Lecture,
    attendanceStatus: AttendanceStatusEnum.Excused,
    assignmentStatus: AssignmentStatusEnum.Overdue,
  },
  {
    id: "18",
    date: new Date(2025, 1, 24, 10, 35),
    subjectName: "Computer Science",
    teacherName: "Michael Johnson",
    teacherAvatar: "https://example.com/avatar2.jpg",
    link: "https://example.com/cs",
    type: LessonTypeEnum.Practice,
    attendanceStatus: AttendanceStatusEnum.Skipped,
    assignmentStatus: AssignmentStatusEnum.Submitted,
  },
  {
    id: "19",
    date: new Date(2025, 1, 24, 12, 20),
    subjectName: "History",
    teacherName: "Emma Wilson",
    teacherAvatar: "https://example.com/avatar3.jpg",
    link: "https://example.com/history",
    type: LessonTypeEnum.Seminar,
    attendanceStatus: AttendanceStatusEnum.Cancelled,
    assignmentStatus: AssignmentStatusEnum.Graded,
  },
  {
    id: "20",
    date: new Date(2025, 1, 24, 14, 5),
    subjectName: "Mathematics",
    teacherName: "John Doe",
    teacherAvatar: "https://example.com/avatar4.jpg",
    link: "https://example.com/math",
    room: "A101",
    type: LessonTypeEnum.Consultation,
    attendanceStatus: AttendanceStatusEnum.Unknown,
    assignmentStatus: AssignmentStatusEnum.Expired,
  },
  {
    id: "21",
    date: new Date(2025, 2, 1, 8, 40),
    subjectName: "Math",
    teacherName: "John Doe",
    teacherAvatar: "https://example.com/avatar.jpg",
    link: "https://example.com",
    room: "A101",
    type: LessonTypeEnum.Lecture,
    attendanceStatus: AttendanceStatusEnum.Attended,
    assignmentStatus: AssignmentStatusEnum.Due,
  },
  {
    id: "22",
    date: new Date(2025, 2, 1, 10, 35),
    subjectName: "Math",
    teacherName: "John Doe",
    teacherAvatar: "https://example.com/avatar.jpg",
    link: "https://example.com",
    room: "A101",
    type: LessonTypeEnum.Lecture,
    attendanceStatus: AttendanceStatusEnum.Attended,
  },
];

const baseDate = new Date(1970, 0, 1);
const timeSlots: [Date, Date][] = [
  [
    setHours(setMinutes(new Date(baseDate), 40), 8),
    setHours(setMinutes(new Date(baseDate), 15), 10),
  ],
  [
    setHours(setMinutes(new Date(baseDate), 35), 10),
    setHours(setMinutes(new Date(baseDate), 10), 12),
  ],
  [
    setHours(setMinutes(new Date(baseDate), 20), 12),
    setHours(setMinutes(new Date(baseDate), 55), 13),
  ],
  [
    setHours(setMinutes(new Date(baseDate), 5), 14),
    setHours(setMinutes(new Date(baseDate), 40), 15),
  ],
  [
    setHours(setMinutes(new Date(baseDate), 50), 15),
    setHours(setMinutes(new Date(baseDate), 25), 17),
  ],
  [
    setHours(setMinutes(new Date(baseDate), 35), 17),
    setHours(setMinutes(new Date(baseDate), 20), 19),
  ],
];

const TimetablePage = () => {
  const { selectedDate } = useDate();
  const startOfCurrentWeek = useMemo(
    () => startOfWeek(selectedDate || new Date(), { weekStartsOn: 1 }),
    [selectedDate]
  );

  return (
    <Timetable
      lessons={lessons}
      timeSlots={timeSlots}
      startOfWeek={startOfCurrentWeek}
    />
  );
};
export default TimetablePage;
